Scripts of database backups
AASF-IIITM/aasf-website-backend pull request #25
Opened 2020-10-03 20:52 UTC by savi-1311

Solves Issue #9 
The cron job runs weekly to create a dump folder in the scripts folder with database backup.
The changes made-
1. Added scripts folder in the root directory
2. Created scripts/backup.js containing scripts for scheduled backup.
3. Added MONGOURI field in the example .env file.
4. Added require('corn') in server/index.js to run the script.

2020-10-04 03:53 UTC, manishprivet requested changes

2020-10-04 03:53 UTC, manishprivet commented on scripts/backup.js
> +require('dotenv').config('../.env');
The dotenv should be called before or into the entrypoint of the server which is index.js

It should either be in `server/index.js`, or better yet, in the`package.json`, set the start script to 

`node -r dotenv/config dist/index.js`

2020-10-04 03:53 UTC, manishprivet commented on .env.example
> +MONGOURI= mongodb://<username>:<password>@cluster0-shard-00-00-46c53.mongodb.net:27017,cluster0-shard-00-01-46c53.mongodb.net:27017,cluster0-shard-00-02-46c53.mongodb.net:27017/<dbname>?ssl=true&repl
This env seems unnecessary + you accidentally revealed your atlas cluster ID

2020-10-06 15:19 UTC, GunaShekar02 commented
Hey @savi-1311, the scripts look good to go. But as I said, these scripts will run separately, independent of the main server.
Please reverse any changes made to the current server, and you can `npm init` in the scripts folder and start a new server there. Everything related to the scripts will be in the new server itself and that will function independent of the main server. 
So basically all of your script-related code is great, you just have to migrate it to a new server in a new folder(scripts folder) and reverse any changes made to the main server folder.

Marking this PR approved for now, hope to see the changes implemented!

2020-10-06 15:20 UTC, GunaShekar02 approved these changes

2020-10-06 16:43 UTC, savi-1311 commented
@GunaShekar02 Sir I have done the required changes.

2021-09-07 14:19 UTC, closed without merging